# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fall_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poke_source',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poke_target',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
